server:
 port: 8082

spring:
 datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: root
 jpa:
    hibernate:
        ddl-auto: update #enable auto update from models
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
            lob.non-contextual-creation: true #avoid erros
    properties:
        hibernate:
            show_sql: true #show database

ead:
  api:
    url:
      authuser: 'http://localhost:8087'


