server:
 port: 8082
 servlet:
   context-path: '/ead-course/'

spring:
  rabbitmq:
    addresses: amqps://awbmtduh:7a2eDXaxkqDBsFFo0gxboRE7kFdphhAs@toad.rmq.cloudamqp.com/awbmtduh
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: root
  jpa:
    hibernate:
        ddl-auto: update #enable auto update from models
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
            lob.non-contextual-creation: true #avoid erros
    properties:
        hibernate:
            show_sql: true #show database

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost


